DROP TABLE IF EXISTS usuarios;

CREATE TABLE usuarios (
   id INTEGER PRIMARY KEY AUTOINCREMENT,
   email TEXT NOT NULL,
   senha TEXT NOT NULL
);

CREATE TABLE tarefas (
   id INTEGER PRIMARY KEY AUTOINCREMENT,
   titulo TEXT NOT NULL,
   conteudo TEXT NOT NULL
);

CREATE TABLE categorias (
   id INTEGER PRIMARY KEY AUTOINCREMENT,
   nome TEXT NOT NULL
);